name: DigiCoin
author: Flenix
main: co.uk.silvania.cities.digicoin.DigiCoin
version: ${project.version}
depend: [Vault]

commands:
  money:
    description: Economy core command.

permissions:
  digicoin.pay:
    description: Lets you pay a player.
  digicoin.top:
    description: Lets you display the leaderboard.
  digicoin.admin:
    description: Lets you use admin commands.
    default: op